---
title: Village  Coffee Marmion
timezone: Australia/Melbourne
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: 
email: contact@villagecoffee.com.au
description: Teaming that early morning coffee with a great meal and service with
  a smile. Village has everything that the Marmion locals have been waiting for. Coming
  soon.
permalink: pretty
exclude:
- Gemfile.lock
- Gemfile
- README*
- node_modules
- ".gitignore"
- assets/scripts/src
- yarn.lock
- ".git"
- package.json
- package-lock.json
facebook_url: https://www.facebook.com/villagecoffeemarmion/
insta_url: https://www.instagram.com/villagecoffeemarmion/
whitelist:
- jekyll-redirect-from
favicon_image: 
